const env = process.env

module.exports= {
  PORT : env.PORT,
  DB_URI : `${env.DB_URL}${env.DB_NAME}`,
  TOKEN_SECRET : env.TOKEN_SECRET,
  TOKEN_SECRET_ADMIN : env.TOKEN_SECRET_ADMIN,
  TEMPLATE_DIR :env.TEMPLATE_DIR,
  TWILIO_EMAIL_API_KEY :env.TWILIO_EMAIL_API_KEY,
  EMAIL_SUBJECT : env.EMAIL_SUBJECT,
  STATIC_IMAGE_PATH : env.STATIC_IMAGE_PATH,
  STATIC_DESTINATION : env.STATIC_DESTINATION
}